/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.58
 * Generated at: 2024-05-12 04:26:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class calories_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("import java.io.*;\r\n");
      out.write("import javax.servlet.*;\r\n");
      out.write("import javax.servlet.annotation.WebServlet;\r\n");
      out.write("import javax.servlet.http.*;\r\n");
      out.write("import java.sql.*;\r\n");
      out.write("import java.util.*;\r\n");
      out.write("import com.opencsv.CSVReader;\r\n");
      out.write("\r\n");
      out.write("@WebServlet(\"/calories\")\r\n");
      out.write("public class CaloriesServlet extends HttpServlet {\r\n");
      out.write("    private static final long serialVersionUID = 1L;\r\n");
      out.write("\r\n");
      out.write("    private static final String JDBC_URL = \"jdbc:mysql://ec2-3-16-149-43.us-east-2.compute.amazonaws.com:3306/UserData\";\r\n");
      out.write("    private static final String JDBC_USER = \"diethelper_remote\";\r\n");
      out.write("    private static final String JDBC_PASSWORD = \"diethelper\";\r\n");
      out.write("\r\n");
      out.write("    @Override\r\n");
      out.write("    public void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\r\n");
      out.write("        String username = \"username1\"; // Set the username to \"username1\"\r\n");
      out.write("        int totalCalories = 0;\r\n");
      out.write("        \r\n");
      out.write("        try (CSVReader reader = new CSVReader(new FileReader(\"path/to/your/csv/file.csv\"))) {\r\n");
      out.write("            String[] nextLine;\r\n");
      out.write("            while ((nextLine = reader.readNext()) != null) {\r\n");
      out.write("                String foodItem = nextLine[0];\r\n");
      out.write("                int calories = Integer.parseInt(nextLine[1]);\r\n");
      out.write("                \r\n");
      out.write("                String value = request.getParameter(foodItem);\r\n");
      out.write("                if (value != null && value.equals(\"1\")) {\r\n");
      out.write("                    totalCalories += calories;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        } catch (Exception e) {\r\n");
      out.write("            e.printStackTrace();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        try (Connection connection = DriverManager.getConnection(JDBC_URL, JDBC_USER, JDBC_PASSWORD)) {\r\n");
      out.write("            // Store totalCalories in the database or use as needed\r\n");
      out.write("        } catch (SQLException e) {\r\n");
      out.write("            e.printStackTrace();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        response.sendRedirect(request.getContextPath() + \"/calorieCounter\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @Override\r\n");
      out.write("    public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\r\n");
      out.write("        response.setContentType(\"text/html;charset=UTF-8\");\r\n");
      out.write("        PrintWriter out = response.getWriter();\r\n");
      out.write("\r\n");
      out.write("        // Display form with food items and checkboxes for user selection\r\n");
      out.write("        out.println(\"<html><head><title>Calorie Counter</title></head>\");\r\n");
      out.write("        out.println(\"<body>\");\r\n");
      out.write("        out.println(\"<h2>Food Items and Calorie Counter</h2>\");\r\n");
      out.write("        out.println(\"<form method='post'>\");\r\n");
      out.write("\r\n");
      out.write("        try (CSVReader reader = new CSVReader(new FileReader(\"path/to/your/csv/file.csv\"))) {\r\n");
      out.write("            String[] nextLine;\r\n");
      out.write("            while ((nextLine = reader.readNext()) != null) {\r\n");
      out.write("                String foodItem = nextLine[0];\r\n");
      out.write("                out.println(\"<input type='checkbox' name='\" + foodItem + \"' value='1'>\" + foodItem + \"<br>\");\r\n");
      out.write("            }\r\n");
      out.write("        } catch (Exception e) {\r\n");
      out.write("            e.printStackTrace();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        out.println(\"<input type='submit' value='Calculate Total Calories'>\");\r\n");
      out.write("        out.println(\"</form>\");\r\n");
      out.write("        out.println(\"</body></html>\");\r\n");
      out.write("    }\r\n");
      out.write("}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
